<?php

namespace ContainerH6Upy5i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BQWnx3dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bQWnx3d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bQWnx3d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'concoursRepository' => ['privates', 'App\\Repository\\ConcoursRepository', 'getConcoursRepositoryService', true],
            'epreuvesRepository' => ['privates', 'App\\Repository\\EpreuvesRepository', 'getEpreuvesRepositoryService', true],
        ], [
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
            'concoursRepository' => 'App\\Repository\\ConcoursRepository',
            'epreuvesRepository' => 'App\\Repository\\EpreuvesRepository',
        ]);
    }
}
