<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH6Upy5i\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH6Upy5i/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH6Upy5i.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH6Upy5i\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH6Upy5i\App_KernelDevDebugContainer([
    'container.build_hash' => 'H6Upy5i',
    'container.build_id' => '8e77fb9d',
    'container.build_time' => 1696259699,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH6Upy5i');
